config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:index]
  root "home#index"
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.image = auth.info.image
      user.profile = auth.info.urls.Google
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.where(pvt: false)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = (Post.all.where(pvt: false) + current_user.posts if current_user).uniq
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js              
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :pvt)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to posts_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<div class="container">

  <div class="row" id="container_posts">
    <%= render @posts %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Note Plus</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
</br>
</br>
<div class="row">
  <div class="col-md-2 col-md-offset-5">
    <% if current_user %>
        Hey <strong><%= current_user.name %></strong> <%= current_user.email%>
        </br>
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
    <% end %>
  </div>
</div>
</br>
</br>
<div>
  <%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :private %>
    <%= f.check_box :pvt %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col-md-4 blog-main box text-center" id="post_<%= post.id%>">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title"><%= %><%= post.title %></h3>
		</div>
		<div class="panel-body">
          <p><%= post.content %></p>
			<div style="color: #3BB206;"><%= time_ago_in_words(post.created_at) %></div>
			<% if current_user && post.user_id == current_user.id %>
              <div class="btn-group" role="group" aria-label="...">
                <button type="button" data-toggle="modal" data-target="#myupdatepost_<%=post.id%>">Edit</button>
                <%= button_to "Delete", post, method: :delete, data: {confirm: "Are you sure?"}, remote:true %>
              </div>
            <% end %>
		</div>
	</div>

	<%= form_for(post, :method => :put, remote: true) do |f| %>
    <div class="modal fade" id="myupdatepost_<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Edit</h4>
          </div>
          <div class="modal-body">

            <div class="field">
              <%= f.label :title %>
              <%= f.text_area :title, class: "form-control"%>
            </div>

            <div class="field">
              <%= f.label :content %>
              <%= f.text_area :content, class: "form-control"%>
            </div>
            <div class="field">
              <%= f.label :private %>
              <%= f.check_box :pvt, class: "form-control"%>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">Close</button>
            <%= submit_tag "Update", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/create.js.erb
$("#mynewpost").modal('hide');
$(".post_title").val('');
$(".post_content").val('');
$("#container_posts").prepend('<%= j render @post %>');
$("#post_<%= @post.id %>").hide().fadeIn(1000);

app/views/posts/destroy.js.erb
$("#post_<%= @post.id%>").fadeOut(500, function(){
	$(this).remove();
});

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">
      <br>
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#mynewpost">
        Create New Note
      </button>
      <br>
      <br>
    </div>
  </div>

  <div class="row" id="container_posts">
    <%= render @posts %>
  </div>

  <%= form_for(@post, remote: true) do |f| %>
    <div class="modal fade" id="mynewpost" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Posts</h4>
          </div>
          <div class="modal-body">

            <div class="field">
              <%= f.label :title %>
              <%= f.text_area :title, class: "form-control post_title"%>
            </div>

            <div class="field">
              <%= f.label :content %>
              <%= f.text_area :content, class: "form-control post_content"%>
            </div>
            <div class="field">
              <%= f.label :private %>
              <%= f.check_box :pvt %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">Close</button>
            <%= submit_tag "Create", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/update.js.erb
$("#myupdatepost_<%= @post.id %>").modal('hide');
$("#post_<%= @post.id%>").fadeOut(500, function(){
	$(this).remove();
	$("#container_posts").prepend('<%= j render @post %>')
});